# Configuração geral
spring.application.name=appcheckup

# Ativação de perfis
# Por padrão, ativa o perfil dev
spring.profiles.active=dev

# Configurações comuns do Jackson
# spring.jackson.serialization.write-dates-as-timestamps=false
